[package]
name = "cli"
version.workspace = true
license.workspace = true
edition.workspace = true
publish = false

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true, features = ["derive"] }
ionic = { package = "ionic-rs", path = "../parser", version = "0.2.0" }
regex = { workspace = true }
rayon = { workspace = true }
mimalloc = { version = "0.1.52" }
crc32fast = "1.5.2"
memmap2 = "0.9"
cosmoz = { workspace = true }

[[bin]]
name = "ionic"
path = "src/main.rs"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
tempfile = "3"
