[package]
name = "ionic"
version.workspace = true
license.workspace = true
edition = "2024"

[dependencies]
serde = { workspace = true }
base64 = { workspace = true }
miniz_oxide = { workspace = true }
once_cell = { workspace = true }
quick-xml = { workspace = true }
serde_json = { workspace = true }
hashbrown = "0.17.1"
itoa = { workspace = true }
crc32fast = "1.5.0"
sha1 = "0.11"
bytemuck = "1"

[target.'cfg(not(all(target_arch = "wasm32", not(target_os = "wasi"))))'.dependencies]
zstd = { workspace = true }
rayon = { workspace = true }
memmap2 = "0.9"

[target.'cfg(all(target_arch = "wasm32", not(target_os = "wasi")))'.dependencies]
osmo = { workspace = true, features = ["std"] }

[dev-dependencies]
proptest = "1"
sha1 = "0.11"
